###
GET http://localhost:3027/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmluc2hpZGhhIGsiLCJpYXQiOjE3MTY1OTg5MzN9.qAK3TWW6i_x20E3hxz3KeJXzM2YiEOQ2PPJqc9N78Jg


###
POST http://localhost:3027/login HTTP/1.1
Content-Type: application/json

{
    "name":"Binshidha k",
    "password":"abc123"
}


###
GET http://localhost:3027/api/user/624908f5b5e11f2868a5d47c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmluc2hpZGhhIGsiLCJpYXQiOjE3MTY1OTg5MzN9.qAK3TWW6i_x20E3hxz3KeJXzM2YiEOQ2PPJqc9N78Jg

###

DELETE http://localhost:3027/api/user/6254e00544e030de06a39912
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmluc2hpZGhhIGsiLCJpYXQiOjE3MTY1OTg5MzN9.qAK3TWW6i_x20E3hxz3KeJXzM2YiEOQ2PPJqc9N78Jg

###

POST http://localhost:3027/register
content-type: application/json

{
    "name": "Ronaldo",
    "email": "rono@gmail22.com",
    "password":"leo1234",
}

###
get http://localhost:3027/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmluc2hpZGhhIGsiLCJpYXQiOjE3MTY1OTg5MzN9.qAK3TWW6i_x20E3hxz3KeJXzM2YiEOQ2PPJqc9N78Jg


###
POST http://localhost:3027/api/post/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmluc2hpZGhhIGsiLCJpYXQiOjE3MTY1OTg5MzN9.qAK3TWW6i_x20E3hxz3KeJXzM2YiEOQ2PPJqc9N78Jg

{
    "title": "Python",
    "description": "Python is a high-level, general-purpose programming language",
    "author":"62490e4b68a25c2a367057eb"
}

###
GET http://localhost:3027/api/post/665198be39baf2a36cc54266
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmluc2hpZGhhIGsiLCJpYXQiOjE3MTY1OTg5MzN9.qAK3TWW6i_x20E3hxz3KeJXzM2YiEOQ2PPJqc9N78Jg


###
get http://localhost:3027/api/post/user/62490e4b68a25c2a367057eb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmluc2hpZGhhIGsiLCJpYXQiOjE3MTY1OTg5MzN9.qAK3TWW6i_x20E3hxz3KeJXzM2YiEOQ2PPJqc9N78Jg
